function Pic_out=scale_change(Pic_in,blksize)
%%
[m, n]=size(Pic_in);
%%
himpad = vision.ImagePadder('Method', 'Symmetric', ...
'RowPaddingLocation', 'Both top and bottom', ...
'NumPaddingRows', floor(blksize/2), ...
'ColumnPaddingLocation', 'Both left and right', ...
'NumPaddingColumns',floor(blksize/2));
%%
Pic_out = step(himpad,Pic_in);